import test from 'node:test';import assert from 'node:assert/strict';import {fork} from 'node:child_process';import {once} from 'node:events';import {mkdtempSync,rmSync} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {mailTaskFixture} from './fixtures/mail-task-fixture.js';import type {MailCancelInput} from '../src/mail-cancellation-contract.js';
for(const stage of ['beforePersist','afterTransition','afterPersist'])test(`SIGKILL ${stage}: atomic cancellation recovery and replay`,{timeout:20000},async()=>{
 const dir=mkdtempSync(join(tmpdir(),'p10-crash-')),child=fork(new URL('./fixtures/mail-cancellation-crash.ts',import.meta.url),[dir,stage],{execArgv:['--import','tsx'],stdio:['ignore','ignore','pipe','ipc']});let timer:ReturnType<typeof setTimeout>|undefined,stderr='';child.stderr?.on('data',b=>stderr+=String(b));
 try{const [data]=await Promise.race([once(child,'message'),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('CRASH_TIMEOUT '+stderr)),10000);child.once('exit',()=>reject(new Error('CRASH_EXIT '+stderr)));})]);if(timer)clearTimeout(timer);const {id,input}=data as {id:string;input:MailCancelInput};const exit=once(child,'exit');child.kill('SIGKILL');const [,signal]=await exit;assert.equal(signal,'SIGKILL');
  const f=await mailTaskFixture({dir});try{const v=await f.client.emailWorkflow(id);assert.equal(v.status,stage==='afterPersist'?'cancelled':'approved');assert.equal(v.cancellation!==null,stage==='afterPersist');assert.equal(v.audit.filter(a=>a.type==='job.cancelled.user').length,stage==='afterPersist'?1:0);assert.equal(v.decision!.decision,'approved');assert.equal(f.sender.counts().calls,0);
   const c=await f.client.cancelEmailTask(id,input);assert.equal(c.status,'cancelled');assert.equal(c.audit.filter(a=>a.type==='job.cancelled.user').length,1);const state=f.runtime.kernel.snapshot();await f.reopen();assert.deepEqual(f.runtime.kernel.snapshot(),state);await assert.rejects(f.client.emailWorkflow(id,'execute'));assert.equal(f.sender.counts().calls,0);
  }finally{await f.done();}
 }finally{if(timer)clearTimeout(timer);child.kill('SIGKILL');rmSync(dir,{recursive:true,force:true});}
});
