import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {GmailLocalConnector} from '../src/gmail-local-connector.js';import {TestVault} from './fixtures/gmail-runtime.js';import {GMAIL_SEND_SCOPE,GMAIL_READ_SCOPE} from '../src/gmail-oauth.js';
import {InboxService} from '../src/inbox-service.js';import {InboxStore} from '../src/inbox-store.js';import {historyGmail,msg,NOW} from './fixtures/gmail-history-fake.js';import {P04_SCOPE,P04_OPTIONS} from './fixtures/inbox-p04-scenarios.js';import {mailTaskProposal} from './fixtures/mail-task-fixture.js';
import {openWorkspaceRuntime} from '../src/runtime-source.js';import {WorkspaceApi,InMemoryWorkspaceRepository} from '../src/workspace-api.js';import {WorkspaceClient} from '../src/workspace-client.js';import {handlePymesRequest} from '../src/api-server.js';
test('Gmail source → approval → actual Gmail adapter sends threadId + exact reply headers; thread mismatch stays UNKNOWN',async()=>{
 for(const mismatch of [false,true]){
  const dir=mkdtempSync(join(tmpdir(),'mail-gmail-thread-')),vault=new TestVault(),history=historyGmail([msg('in1',{subject:'Consulta RC',body:'Necesito responsabilidad civil para mi actividad.'})]);let sends=0,raw='',thread='';
  const fetcher:typeof fetch=async(i,o)=>{const u=new URL(String(i));if(u.pathname.endsWith('/messages/send')){sends++;const b=JSON.parse(String(o?.body));raw=b.raw;thread=b.threadId;return Response.json({id:'sent1'});}if(u.pathname.endsWith('/messages/sent1'))return Response.json({id:'sent1',labelIds:['SENT'],threadId:mismatch?'wrong-thread':thread,raw});if(u.pathname.endsWith('/messages')&&u.searchParams.get('q')?.includes('rfc822msgid'))return Response.json({messages:[{id:'sent1'}]});if(u.pathname.endsWith('/messages')&&u.searchParams.get('labelIds')==='SENT'&&!u.searchParams.has('includeSpamTrash'))return Response.json({messages:[{id:'sent1'}]});return history.fetcher(i,o);};
  const gmail=new GmailLocalConnector('owner','agency',join(dir,'claims.db'),vault,async()=>{},fetcher);
  await vault.set(gmail.oauth.credentialRef,JSON.stringify({accessToken:'synthetic-access',refreshToken:'synthetic-refresh',expiresAt:Date.now()+3600000,clientId:'test.apps.googleusercontent.com',clientSecret:'synthetic-client',account:'owner@example.test',subject:'account-one',scopes:[GMAIL_SEND_SCOPE,GMAIL_READ_SCOPE,'openid','email'],generation:'b'.repeat(64)}));await gmail.status('owner');
  const store=new InboxStore(join(dir,'inbox.db'),()=>NOW),inbox=new InboxService(gmail.oauth,store,P04_SCOPE,fetcher,P04_OPTIONS,()=>NOW);await inbox.syncNow();
  const runtime=await openWorkspaceRuntime(join(dir,'runtime.db'),'agency',{gmail,gmailInbox:inbox,mailProposalProvider:{id:'synthetic-local',proposeJson:async()=>({value:mailTaskProposal(),model:'fixture',latencyMs:1})}}),api=new WorkspaceApi(new InMemoryWorkspaceRepository(),undefined,runtime.source);api.addSession('synthetic-owner-token-123456789',{tenantId:'agency',userId:'owner',role:'owner'});const client=new WorkspaceClient({baseUrl:'http://127.0.0.1',tenantId:'agency',token:'synthetic-owner-token-123456789'},(i,o)=>handlePymesRequest(api,new Request(String(i),o)));
  try{
   const ref=(await inbox.context(null)).info!.accountRef;
   await client.crmCommand({commandId:'c',expectedRevision:0,operation:{type:'contact.create',id:'c',name:'Synthetic client',email:'cliente@example.test',phone:'',notes:'',relationship:'prospect'}});await client.crmResolve(ref,'in1');const proposal=(await client.mailAssistance(ref,'in1','generate')).proposal!;await client.mailAssistance(ref,'in1','review',{proposalId:proposal.id,decision:'accepted'});
   const task=(await client.mailTask(ref,'in1',{accountRef:ref,gmailId:'in1',proposalId:proposal.id,contactId:'c',to:'cliente@example.test',subject:'Re: Consulta RC',body:'Texto aprobado.',recipientReviewed:true,followUpTitle:'Llamar al cliente',followUpDueAt:Date.now()+86400000})).taskId!,review=await client.emailWorkflow(task,'review');await client.emailWorkflow(task,'decision',{bindingHash:review.review!.bindingHash,decision:'approved'});const sent=await client.emailWorkflow(task,'execute');
   assert.equal(thread,'tin1');assert.match(Buffer.from(raw,'base64url').toString(),/In-Reply-To: <in1@example.test>\r\nReferences: <in1@example.test>/);assert.equal(sent.status,mismatch?'unknown':'completed');assert.equal(sent.simulated,false);assert.equal((await client.crm({contactId:'c'})).followUps.length,mismatch?0:1);
   await client.emailWorkflow(task,'execute');assert.equal(sends,1);
  }finally{await inbox.close();runtime.close();gmail.close();store.close();rmSync(dir,{recursive:true,force:true});}
 }
});
