import test from 'node:test';
import assert from 'node:assert/strict';
import {TaskRuntimeKernel,readRuntimeWorkspace,type TaskRuntimeEvent} from '../src/index.js';
function fixture(){const kernel=new TaskRuntimeKernel();let seq=0;const send=(body:Record<string,unknown>,taskId='t')=>kernel.apply({id:`e${++seq}`,at:seq,taskId,...body} as TaskRuntimeEvent,kernel.snapshot().revision);
 const criterion={id:'c',kind:'test',command:'private command',expectedExitCode:0};
 send({type:'GlobalTaskCreated',goal:'Prepare draft',owner:'owner',successCriteria:[criterion],contextRootRef:'private-context'});
 send({type:'GlobalTaskCreated',goal:'Other customer secret',owner:'other',successCriteria:[criterion]},'foreign');
 send({type:'GlobalTaskPlanningStarted'});send({type:'PlanCommitted',planVersion:1,workUnits:[{id:'u',title:'Draft',objective:'private objective',dependencies:[],requiredCapabilities:[],constraints:[],expectedArtifacts:[],successCriteria:[criterion]}]});
 send({type:'AttemptCreated',workUnitId:'u',attemptId:'a',providerId:'orca',actorId:'worker',dispatchFingerprint:'secret-fingerprint'});send({type:'AttemptReserved',attemptId:'a'});send({type:'AttemptDispatchStarted',attemptId:'a'});send({type:'AttemptProviderReported',attemptId:'a',outcome:'succeeded'});return {kernel,send};}
test('runtime view is owner scoped and distinguishes provider report from verified success',()=>{const {kernel}=fixture();const view=readRuntimeWorkspace(kernel.snapshot(),'owner');assert.equal(view.tasks.length,1);assert.equal(view.tasks[0]!.status,'verifying');assert.equal(view.tasks[0]!.counts.succeeded,0);assert.equal(view.tasks[0]!.units[0]!.attempts[0]!.reportedOutcome,'succeeded');const encoded=JSON.stringify(view);for(const secret of ['private command','private-context','private objective','secret-fingerprint','Other customer secret'])assert.equal(encoded.includes(secret),false);assert.deepEqual(readRuntimeWorkspace(kernel.snapshot(),'owner',{taskId:'foreign'}).tasks,[]);});
test('view preserves unknown and detached evidence history',()=>{const {kernel,send}=fixture();send({type:'VerificationStarted',attemptId:'a'});send({type:'EvidenceRecorded',attemptId:'a',referenceId:'evidence'});send({type:'VerificationCompleted',attemptId:'a',results:[{criterionId:'c',status:'unknown',evidenceRefs:['evidence']}]});const view=readRuntimeWorkspace(kernel.snapshot(),'owner');assert.equal(view.tasks[0]!.status,'unknown');assert.equal(view.tasks[0]!.counts.unknown,1);view.tasks[0]!.verifications[0]!.results[0]!.evidenceRefs.push('tampered');assert.deepEqual(kernel.snapshot().verifications[0]!.results[0]!.evidenceRefs,['evidence']);});
test('invalid identity and unbounded list limits are rejected',()=>{const {kernel}=fixture();assert.throws(()=>readRuntimeWorkspace(kernel.snapshot(),''));assert.throws(()=>readRuntimeWorkspace(kernel.snapshot(),'owner',{limit:101}));assert.equal(readRuntimeWorkspace(kernel.snapshot(),'missing').tasks.length,0);});
