export type BudgetErrorCode =
  | "BUDGET_NOT_FOUND" | "BUDGET_NOT_ACTIVE" | "BUDGET_FROZEN"
  | "BUDGET_CLOSED" | "BUDGET_EXPIRED" | "BUDGET_HAS_ACTIVE_RESERVATIONS"
  | "BUDGET_ALREADY_EXISTS" | "INVALID_BUDGET_VECTOR"
  | "NEGATIVE_BUDGET_QUANTITY" | "INVALID_BUDGET_QUANTITY"
  | "UNKNOWN_BUDGET_DIMENSION" | "INSUFFICIENT_BUDGET"
  | "RESERVATION_NOT_FOUND" | "RESERVATION_NOT_ACTIVE"
  | "RESERVATION_EXPIRED" | "RESERVATION_ALREADY_COMMITTED"
  | "RESERVATION_ALREADY_RELEASED" | "RESERVATION_ALREADY_EXISTS"
  | "ACTUAL_EXCEEDS_RESERVATION" | "PRINCIPAL_MISMATCH"
  | "TASK_MISMATCH" | "VERSION_CONFLICT" | "INVARIANT_VIOLATION"
  | "INVALID_TIME_WINDOW" | "INVALID_IDENTITY" | "CHILD_BUDGET_ACTIVE";

export class BudgetError extends Error {
  constructor(readonly code: BudgetErrorCode, detail?: string) {
    super(detail ? `${code}:${detail}` : code);
    this.name = "BudgetError";
  }
}
